name: Release & Publish

on:
  push:
    tags:
      - 'v*'

permissions: 
      contents: write
      packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kmedara/express-problem-details'
      # - run: npm run addscope
      # - name: Version
      #   run: |
      #     git config --global user.email "kmedara2015@outlook.com"
      #     git config --global user.name "Kevin Medara"
      #     # npm version ${{github.ref_name}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}