name: Release & Publish

on:
  push:
    tags:
      - 'v*'

permissions: 
      contents: write
      packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kmedara/express-problem-details'
      
      - name: Obtain Version
        uses: bhowell2/github-substring-action@1.0.2
        id: two
        with:
          value: ${{ github.ref_name }}
          length_from_start: 1

      - name: Version
        env: 
          VERSION: ${{ github.ref_name }}
        run: |
          git config --global user.email "kmedara2015@outlook.com"
          git config --global user.name "Kevin Medara"
          npm version 2.0.0

        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}